Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,20 +1,25 @@
-# Fast fail the script on failures.
-set -e
-# Get Dart SDK
-mkdir travis
-echo "Home:"
-echo $HOME
-export TRAVIS_HOME="${HOME}/travis"
-echo "Travis home:"
-echo $TRAVIS_HOME
-curl -o sdk.zip https://storage.googleapis.com/dart-archive/channels/stable/release/2.0.0/sdk/dartsdk-windows-x64-release.zip > ${TRAVIS_HOME}/dartsdk.zip"
-unzip ${TRAVIS_HOME}/dartsdk.zip -d ${TRAVIS_HOME} > /dev/null
-rm ${TRAVIS_HOME}/dartsdk.zip
-export DART_SDK="${TRAVIS_HOME}/dart-sdk"
-echo "Path 1:"
-echo $PATH
-export PATH="$DART_SDK/bin:$PATH"
-export PATH="${TRAVIS_HOME}/.pub-cache/bin:$PATH"
-echo "Path 2:"
-echo $PATH
-dart --version
+language: bash
+os:
+  - windows
+sudo: false
+script:
+  - # Fast fail the script on failures.
+  - set -e
+  - # Get Dart SDK
+  - mkdir travis
+  - echo "Home:"
+  - echo $HOME
+  - export TRAVIS_HOME="${HOME}/travis"
+  - echo "Travis home:"
+  - echo $TRAVIS_HOME
+  - curl -o sdk.zip https://storage.googleapis.com/dart-archive/channels/stable/release/2.0.0/sdk/dartsdk-windows-x64-release.zip > ${TRAVIS_HOME}/dartsdk.zip"
+  - unzip ${TRAVIS_HOME}/dartsdk.zip -d ${TRAVIS_HOME} > /dev/null
+  - rm ${TRAVIS_HOME}/dartsdk.zip
+  - export DART_SDK="${TRAVIS_HOME}/dart-sdk"
+  - echo "Path 1:"
+  - echo $PATH
+  - export PATH="$DART_SDK/bin:$PATH"
+  - export PATH="${TRAVIS_HOME}/.pub-cache/bin:$PATH"
+  - echo "Path 2:"
+  - echo $PATH
+  - dart --version
